### ISSUE TITLE
序列化报错

### ISSUE THREAD

**Issue by hyb200** [liyupi/yu-rpc#3]
鱼总，项目简单敲了一遍，但是消费者无法成功调用服务，报错：
```
java.io.StreamCorruptedException: invalid stream header: 54686973
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:938)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:396)
	at com.abin.serializer.JdkSerializer.deserialize(JdkSerializer.java:19)
	at com.abin.proxy.ServiceProxy.invoke(ServiceProxy.java:47)
	at com.sun.proxy.$Proxy0.getUser(Unknown Source)
	at com.abin.consumer.SimpleConsumer.main(SimpleConsumer.java:16)
```
这该怎么解决？

**Comment by liyupi** [comment]
可能是版本的问题，换一个序列化器实现吧，重点还是学习 SPI 机制的设计
